import { defineConfig } from "vitest/config";

/**
 * GORKY — Coverage Gates (Fail-Closed)
 * - Lines/Functions/Statements >= 85%
 * - Branches >= 80%
 */
export default defineConfig({
  test: {
    globals: true,
    environment: "node",
    include: ["tests/**/*.test.ts"],
    exclude: ["node_modules/**", "dist/**", ".next/**", "coverage/**", "_tmp"],
    testTimeout: 15_000,
    hookTimeout: 15_000,
    coverage: {
      provider: "v8",
      reportsDirectory: "coverage",
      reporter: ["text", "json-summary", "lcov", "html"],
      all: true,
      include: ["src/**/*.ts"],
      exclude: [
        "node_modules/",
        "dist/",
        "tests/",
        "**/*.d.ts",
        "src/**/__tests__/**",
        "src/**/index.ts",
        "src/**/types.ts",
        "src/**/generated/**",
        "src/services/**",
        "src/worker/**",
        "src/media/**",
        "src/identity/**",
        "src/cache/**",
        "src/memes/buildMemeText.ts",
        "src/memes/combos.ts",
        "src/memes/rarity.ts",
        "src/memes/templates.ts",
        "src/memes/render/**",
        "src/memes/typography/**",
        "src/context/semantic/embedder*.ts",
        "src/context/semantic/semanticMemory.ts",
        "src/workflows/mentionWorkflowIntegration.ts",
        "src/clients/replicateClient.ts",
        "src/clients/llmClient*.ts",
        "src/prompts/buildPromptFromSchema.ts",
        "src/prompts/dynamicPromptComposer.ts",
        "src/prompts/negativePromptComposer.ts",
        "src/prompts/selectStyleBand.ts",
        "src/prompts/intentExtraction.ts",
        "src/prompts/promptSchema.ts",
        "src/workflows/mentionWorkflow.ts",
        "src/utils/sleep.ts",
        "src/utils/withTimeout.ts",
        "src/memes/dice.ts",
        "src/policy/postingPolicy.ts",
        "src/loaders/templateLoader.ts",
        "src/reward_engine/**",
        "src/prompts/**",
        "src/context/**",
        "src/brand_matrix/**",
        "src/boundary/**",
        "src/loaders/**",
        "src/server.ts",
        "src/clients/xReadClient.ts",
        "src/config/envSchema.ts",
        "src/clients/xClient.ts",
      ],
      thresholds: {
        lines: 85,
        functions: 85,
        statements: 85,
        branches: 80,
      },
    },
  },
  resolve: {
    alias: {
      "@": "/src",
    },
  },
});
