/**
 * Organoid embodiment feature config.
 *
 * No legacy compatibility toggle, no alias fallback, and no parallel identity path.
 */

export interface EmbodimentsConfig {
  EMBODIMENTS_ENABLED: boolean;
  DEFAULT_SAFE_EMBODIMENT: string;
  EMBODIMENT_MEMORY_ENABLED: boolean;
  EMBODIMENT_ROUTING_DEBUG: boolean;
  EMBODIMENT_ORCHESTRATION_ENABLED: boolean;
  EMBODIMENT_CONTINUITY_ENABLED: boolean;
  EMBODIMENT_EVOLUTION_ENABLED: boolean;
  EMBODIMENT_RUNNING_JOKES_ENABLED: boolean;
  EMBODIMENT_SWARM_ENABLED: boolean;
  EMBODIMENT_TRAIT_DRIFT_LIMIT: number;
  EMBODIMENT_ENSEMBLE_ENABLED: boolean;
  EMBODIMENT_AUTONOMY_ENABLED: boolean;
  EMBODIMENT_ARC_ENGINE_ENABLED: boolean;
  EMBODIMENT_MAX_CAMEOS: number;
  EMBODIMENT_WORLD_ENABLED: boolean;
  EMBODIMENT_FACTIONS_ENABLED: boolean;
  EMBODIMENT_WORLD_EVENTS_ENABLED: boolean;
  EMBODIMENT_RITUALS_ENABLED: boolean;
  EMBODIMENT_LORE_EXPANSION_ENABLED: boolean;
}

const DEFAULTS: EmbodimentsConfig = {
  EMBODIMENTS_ENABLED: true,
  DEFAULT_SAFE_EMBODIMENT: "stillhalter",
  EMBODIMENT_MEMORY_ENABLED: false,
  EMBODIMENT_ROUTING_DEBUG: false,
  EMBODIMENT_ORCHESTRATION_ENABLED: false,
  EMBODIMENT_CONTINUITY_ENABLED: true,
  EMBODIMENT_EVOLUTION_ENABLED: false,
  EMBODIMENT_RUNNING_JOKES_ENABLED: false,
  EMBODIMENT_SWARM_ENABLED: false,
  EMBODIMENT_TRAIT_DRIFT_LIMIT: 0.25,
  EMBODIMENT_ENSEMBLE_ENABLED: false,
  EMBODIMENT_AUTONOMY_ENABLED: false,
  EMBODIMENT_ARC_ENGINE_ENABLED: false,
  EMBODIMENT_MAX_CAMEOS: 2,
  EMBODIMENT_WORLD_ENABLED: false,
  EMBODIMENT_FACTIONS_ENABLED: false,
  EMBODIMENT_WORLD_EVENTS_ENABLED: false,
  EMBODIMENT_RITUALS_ENABLED: false,
  EMBODIMENT_LORE_EXPANSION_ENABLED: false,
};

let cached: EmbodimentsConfig | null = null;

function readBoolean(value: string | undefined, fallback: boolean): boolean {
  if (value === undefined) return fallback;
  return value === "true";
}

function readNumber(value: string | undefined, fallback: number): number {
  if (value === undefined || value.trim() === "") return fallback;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

export function getEmbodimentsConfig(): EmbodimentsConfig {
  if (cached) return cached;

  cached = {
    EMBODIMENTS_ENABLED: readBoolean(process.env.EMBODIMENTS_ENABLED, DEFAULTS.EMBODIMENTS_ENABLED),
    DEFAULT_SAFE_EMBODIMENT: process.env.DEFAULT_SAFE_EMBODIMENT ?? DEFAULTS.DEFAULT_SAFE_EMBODIMENT,
    EMBODIMENT_MEMORY_ENABLED: readBoolean(process.env.EMBODIMENT_MEMORY_ENABLED, DEFAULTS.EMBODIMENT_MEMORY_ENABLED),
    EMBODIMENT_ROUTING_DEBUG: readBoolean(process.env.EMBODIMENT_ROUTING_DEBUG, DEFAULTS.EMBODIMENT_ROUTING_DEBUG),
    EMBODIMENT_ORCHESTRATION_ENABLED: readBoolean(process.env.EMBODIMENT_ORCHESTRATION_ENABLED, DEFAULTS.EMBODIMENT_ORCHESTRATION_ENABLED),
    EMBODIMENT_CONTINUITY_ENABLED: readBoolean(process.env.EMBODIMENT_CONTINUITY_ENABLED, DEFAULTS.EMBODIMENT_CONTINUITY_ENABLED),
    EMBODIMENT_EVOLUTION_ENABLED: readBoolean(process.env.EMBODIMENT_EVOLUTION_ENABLED, DEFAULTS.EMBODIMENT_EVOLUTION_ENABLED),
    EMBODIMENT_RUNNING_JOKES_ENABLED: readBoolean(process.env.EMBODIMENT_RUNNING_JOKES_ENABLED, DEFAULTS.EMBODIMENT_RUNNING_JOKES_ENABLED),
    EMBODIMENT_SWARM_ENABLED: readBoolean(process.env.EMBODIMENT_SWARM_ENABLED, DEFAULTS.EMBODIMENT_SWARM_ENABLED),
    EMBODIMENT_TRAIT_DRIFT_LIMIT: readNumber(process.env.EMBODIMENT_TRAIT_DRIFT_LIMIT, DEFAULTS.EMBODIMENT_TRAIT_DRIFT_LIMIT),
    EMBODIMENT_ENSEMBLE_ENABLED: readBoolean(process.env.EMBODIMENT_ENSEMBLE_ENABLED, DEFAULTS.EMBODIMENT_ENSEMBLE_ENABLED),
    EMBODIMENT_AUTONOMY_ENABLED: readBoolean(process.env.EMBODIMENT_AUTONOMY_ENABLED, DEFAULTS.EMBODIMENT_AUTONOMY_ENABLED),
    EMBODIMENT_ARC_ENGINE_ENABLED: readBoolean(process.env.EMBODIMENT_ARC_ENGINE_ENABLED, DEFAULTS.EMBODIMENT_ARC_ENGINE_ENABLED),
    EMBODIMENT_MAX_CAMEOS: readNumber(process.env.EMBODIMENT_MAX_CAMEOS, DEFAULTS.EMBODIMENT_MAX_CAMEOS),
    EMBODIMENT_WORLD_ENABLED: readBoolean(process.env.EMBODIMENT_WORLD_ENABLED, DEFAULTS.EMBODIMENT_WORLD_ENABLED),
    EMBODIMENT_FACTIONS_ENABLED: readBoolean(process.env.EMBODIMENT_FACTIONS_ENABLED, DEFAULTS.EMBODIMENT_FACTIONS_ENABLED),
    EMBODIMENT_WORLD_EVENTS_ENABLED: readBoolean(process.env.EMBODIMENT_WORLD_EVENTS_ENABLED, DEFAULTS.EMBODIMENT_WORLD_EVENTS_ENABLED),
    EMBODIMENT_RITUALS_ENABLED: readBoolean(process.env.EMBODIMENT_RITUALS_ENABLED, DEFAULTS.EMBODIMENT_RITUALS_ENABLED),
    EMBODIMENT_LORE_EXPANSION_ENABLED: readBoolean(process.env.EMBODIMENT_LORE_EXPANSION_ENABLED, DEFAULTS.EMBODIMENT_LORE_EXPANSION_ENABLED),
  };

  return cached;
}

/** Reset cache (for tests). */
export function resetEmbodimentsConfigCache(): void {
  cached = null;
}
